### ISSUE TITLE
PHEindicatormethods rate type - additional option?

### ISSUE THREAD

**Issue by PHEleighdowd** [PublicHealthEngland/PHEindicatormethods#15]
Hi,

I've been using the PHEindicatormethods package to complete some work in R, and I've found that it would be beneficial to me (and maybe others?) if there were an option in which you could receive the output of a count, denominator, value, lower CI and upper CI without gaining the statistic or the method. At present, I am just having to use the type argument FULL and deleting the two unnecessary columns out. 

Is this something that could be considered? 

Cheers!

Leigh

**Comment by PHEgeorginaanderson** [comment]
The type=full will become the default in version 1.1.0.

type = full argument will include all data and metadata fields in output
type = standard argument will drop metadata field but will include all data fields (previously only the value, lowercl and uppercl were included, in addition to input columns.

**Comment by PHEleighdowd** [comment]
That's great! Thanks Georgie :)

**Comment by PHEgeorginaanderson** [comment]
On discussion it is felt this would fit better in a separate package so this issue will be closed.

**Comment by PHEgeorginaanderson** [comment]
complete
