### ISSUE TITLE
Adding z-score function to the PHEindicatormethods package?

### ISSUE THREAD

**Issue by PHEleighdowd** [PublicHealthEngland/PHEindicatormethods#16]
Hi,

Natasha Roberts has requested that we make the R code to calculate the z-scores for the Public Health Dashboard to be made available within a PHE package. Sam Dunn has spoken to Seb Fox about this issue and Seb said that there isn't an official documented process to go through in order to do this, so would be best to raise an issue so that it goes to the methods group.

Cheers,

Leigh

**Comment by PHEgeorginaanderson** [comment]
@PHEleighdowd 
Thanks Leigh  - I will put something in our diaries to discuss the exact requirements with you.

**Comment by PHEgeorginaanderson** [comment]
On discussion it is felt that this feature would sit better in a separate package as it relates specifically to methods applied within the PHE PH Dashboard and not generically.  This issue will be closed.
