### ISSUE TITLE
phe_life_expectancy

### ISSUE THREAD

**Issue by DavidNphe** [PublicHealthEngland/PHEindicatormethods#22]
This may well be user error rather than an issue!

I have a data frame named "multi_area_data" that contains numbers of deaths and populations for four example areas. When I pass this data to the phe_life_expectancy function as follows...

``
LE_multi <- multi_area_data %>%
  group_by(AreaCode, AreaName) %>%
  phe_life_expectancy(multi_area_data, deaths = Deaths, population = Pop,
                      startage = AgeStart, type="standard")
``

I get the following error:

> Error in phe_life_expectancy(., multi_area_data, deaths = Deaths, population = Pop,  : 
  first age band in age_contents must be 0

If I change my code to the following I do not get an error and results are returned as expected:

``
LE_multi <- multi_area_data %>%
  group_by(AreaCode, AreaName) %>%
  phe_life_expectancy(multi_area_data, deaths = Deaths, population = Pop,
                                startage = AgeStart, age_contents = c(0L, 1L, 5L, 10L, 15L, 20L, 25L, 30L, 35L, 40L, 45L,
                                                                      50L, 55L, 60L, 65L, 70L, 75L, 80L, 85L, 90L), type="standard")
``
The only thing I have done differently in the second example is to state the age contents. These are the default options for the age contents argument, so I do not understand why I am having to specify them.

**Comment by PHEgeorginaanderson** [comment]
Hi David - if it's shareable data, can you attach the multi_area_data dataframe as an rda file so I can reproduce your scenario?

**Comment by DavidNphe** [comment]
Hello @PHEgeorginaanderson ,
This issue appears to have fixed itself. As shown in the attached files.
Thanks for responding.
David

[multi_area_example.zip](https://github.com/PublicHealthEngland/PHEindicatormethods/files/3152499/multi_area_example.zip)
