### ISSUE TITLE
Apply rlang embrace {{ }} syntax to SII function

### ISSUE THREAD

**Issue by PHEgeorginaanderson** [PublicHealthEngland/PHEindicatormethods#42]
These functions weren't covered by the updates in v1.2.0

**Comment by sebastian-fox** [comment]
I saw this having fixed #43 so have modified LE code to {{ }} within that PR. I'll change the title of this issue to apply to SII only

**Comment by PHEgeorginaanderson** [comment]
resolved in v 1.3.1
