### ISSUE TITLE
LE outputs unhelpful pops and deaths stats

### ISSUE THREAD

**Issue by PHEgeorginaanderson** [PublicHealthEngland/PHEindicatormethods#52]
@sebastian-fox for info/comment:

The phe_life_expectancy function outputs the original data frame including the input pops and deaths for each specific age bands but once the le calculation has been performed those pops and deaths counts are no longer appropriate since the sum of the pops and deaths from all subsequent age bands are also included in each le-at-age calculation.  

eg it would make more sense to output the sum of deaths and pops in all of the 65+ age bands alongside the le at age 65 statistic, not just the deaths and pop for that specific 65-69 age band.

Or not to output any death and pop counts at all ?

**Comment by sebastian-fox** [comment]
Hi @PHEgeorginaanderson - thanks for the conversation. To confirm, yes, happy for the pops/deaths columns to be output as the sum of pops/deaths with appropriate names.

**Comment by PHEgeorginaanderson** [comment]
Resolved in PHEim version 1.3.1 the new output columns containing aggregate counts for ages equal to or higher than the 'age at' LE are called pops_used and dths_used. The original columns passed to the function containing age-specific pop and death counts are no longer included in the LE output.
