### ISSUE TITLE
set up code coverage badge and tests with GH actions

### ISSUE THREAD

**Issue by sebastian-fox** [publichealthengland/PHEindicatormethods#63]

**Comment by sebastian-fox** [comment]
I have just gone through this process with `fingertipsR`.
```
usethis::use_github_action(name = "test-coverage")
```

I'll then link covr to this repo
Then I'll update the badge in the README

Will do this straight onto master (sorry) as it isn't a risk to the package at all

**Comment by PHEgeorginaanderson** [comment]
Complete
