### ISSUE TITLE
Funnel Plots

### ISSUE THREAD

**Issue by PHEgeorginaanderson** [publichealthengland/PHEindicatormethods#7]
Add Funnel Plot method.  See Matthew Francis funnel plot code.

**Comment by PHEgeorginaanderson** [comment]
Consider best package to put this in - method could go in PHEindicatormethods and chart functionality could go in fingertipscharts?  for dicsussion.....

**Comment by sebastian-fox** [comment]
Funnel plot for proportions added (in merge request currently). Will add additional branch from that merge request to add rates and then ratios

**Comment by PHEgeorginaanderson** [comment]
Complete
